 const haircareData = [
    {
      id: 1,
      category: "haircare",
      name: "Repairing Hair Mask",
      editorRating: 4.9,
      editorReview: "Reduced breakage by 72% in our lab tests after just 3 uses. The ultimate rescue treatment for damaged hair.",
      editorName: "Jamal Williams",
      editorTitle: "Master Stylist",
      price: 38.00,
      image: "/images/products/hair-mask.jpg",
      description: "Intensive reconstructing mask with keratin and amino acids for severely damaged or chemically treated hair.",
      pros: ["Visible results after 1 use", "Color-safe", "5-minute treatment"],
      cons: ["Heavy scent", "Not for fine hair"],
      ratingRank: 1,
      awards: ["Best Splurge", "Beauty Lab Winner"]
    },
    {
      id: 2,
      category: "haircare",
      name: "Revitalizing Shampoo",
      editorRating: 4.6,
      editorReview: "Leaves hair feeling fresh and full, with a lightweight, clean finish.",
      editorName: "Ava Brooks",
      editorTitle: "Haircare Specialist",
      price: 24.00,
      image: "/images/products/shampoo.jpg",
      description: "Shampoo for all hair types that deeply cleanses while maintaining natural oils.",
      pros: ["Gentle", "Moisturizing", "Sulfate-free"],
      cons: ["May not remove heavy product buildup"],
      ratingRank: 2,
      bestFor: ["Everyday Use", "Moisture"]
    },
    {
      id: 3,
      category: "haircare",
      name: "Volume Boosting Spray",
      editorRating: 4.4,
      editorReview: "Adds volume without the crunch or stiffness. The perfect pre-styling product.",
      editorName: "Samantha Lee",
      editorTitle: "Professional Stylist",
      price: 18.50,
      image: "/images/products/volumizing-spray.jpg",
      description: "Lightweight spray that boosts hair volume and texture with a natural finish.",
      pros: ["Adds volume", "Non-greasy", "Works on fine hair"],
      cons: ["Can cause dryness with overuse"],
      ratingRank: 3,
      bestFor: ["Fine Hair", "Volume"]
    },
    {
        id: 4,
        category: "haircare",
        name: "Nourishing Leave-In Conditioner",
        editorRating: 4.8,
        editorReview: "A leave-in conditioner that hydrates and detangles while protecting against heat styling.",
        editorName: "Natalie Scott",
        editorTitle: "Hair Expert",
        price: 15.00,
        image: "/images/products/leave-in-conditioner.jpg",
        description: "Lightweight leave-in treatment that provides intense hydration without weighing down hair.",
        pros: ["Hydrating", "Heat-protectant", "No residue"],
        cons: ["Needs to be used sparingly"],
        ratingRank: 4,
        bestFor: ["Dry Hair", "Heat Protection"]
      },
      {
        id: 5,
        category: "haircare",
        name: "Detangling Hair Brush",
        editorRating: 4.3,
        editorReview: "Smooths through knots with ease, ideal for wet or dry hair without causing damage.",
        editorName: "Lily Rose",
        editorTitle: "Styling Specialist",
        price: 12.50,
        image: "/images/products/detangling-brush.jpg",
        description: "A flexible hairbrush designed to minimize breakage while detangling hair gently.",
        pros: ["Minimizes breakage", "Works for all hair types", "Durable"],
        cons: ["Can be too soft for very thick hair"],
        ratingRank: 5,
        bestFor: ["All Hair Types"]
      }
    ];
    export default haircareData;