const skincareData = [
    {
      id: 675431,
      category: "skincare",
      name: "Cerave Hydrating Foaming Oil",
      editorRating: 4.8,
      editorReview: "Our lab tests confirmed this cleanser removes 99% of impurities without stripping skin. Perfect for sensitive complexions.",
      editorName: "Dr. Emily Chen",
      editorTitle: "Board-Certified Dermatologist",
      price: 28.50,
      image: "/public/cerave.webp",
      description: "A pH-balanced cleanser with ceramides and hyaluronic acid that cleanses while maintaining the skin's moisture barrier.",
      pros: ["Non-drying formula", "Fragrance-free", "Works for all skin types"],
      cons: ["Small bottle size", "Can be pricey for daily use"],
      ratingRank: 5,
      awards: ["Editor's Choice", "Best for Sensitive Skin"]
    },
    {
        id: 788995,
        category: "skincare",
        name: "Kiehl's Deep Pore Cleansing Mask",
        editorRating: 4.9,
        editorReview: "A deep cleansing clay mask that clears pores, removes excess oil, and minimizes blackheads after just one use.",
        editorName: "Dr. Laura Simmons",
        editorTitle: "Board-Certified Dermatologist",
        price: 22.00,
        image: "/public/mask.jpg",
        description: "A clay-based mask with activated charcoal and kaolin to deeply cleanse and purify the skin.",
        pros: ["Detoxifying", "Oil-absorbing", "Brightening"],
        cons: ["Drying", "Can leave a white residue"],
        ratingRank: 4,
        awards: ["Best Pore Cleaner"]
      },
    {
      id: 897642,
      category: "skincare",
      name: "Olay Revitalizing Night Cream",
      editorRating: 4.7,
      editorReview: "A rich night cream that hydrates deeply and visibly reduces fine lines after 2 weeks of use.",
      editorName: "Dr. Sofia Harris",
      editorTitle: "Dermatologist",
      price: 40.00,
      image: "/public/night-cream.avif",
      description: "Intensive night treatment to replenish and firm skin with retinol and peptides.",
      pros: ["Hydrating", "Anti-aging", "Fragrance-free"],
      cons: ["Strong scent", "Can cause irritation for sensitive skin"],
      ratingRank: 3,
      awards: ["Best Night Cream", "Top Anti-Aging Product"]
    },
    {
      id: 6779793,
      category: "skincare",
      name: "Estelin Vitamin C Serum",
      editorRating: 4.6,
      editorReview: "This serum brightens and evens skin tone, leaving a radiant glow with regular use.",
      editorName: "Dr. Isabella Green",
      editorTitle: "Cosmetic Scientist",
      price: 32.50,
      image: "/public/vitc.webp",
      description: "Brightening serum formulated with 15% pure Vitamin C, hyaluronic acid, and ferulic acid for an even complexion.",
      pros: ["Brightening", "Anti-aging", "Fast absorption"],
      cons: ["Can be sticky", "Requires regular use"],
      ratingRank: 2,
      awards: ["Best Brightening Serum"]
    },
    {
      id: 478997,
      category: "skincare",
      name: "Seven Minerals Aloe Vera Gel",
      editorRating: 4.5,
      editorReview: "A refreshing aloe vera gel that calms irritated skin and provides instant relief from sunburn.",
      editorName: "Dr. Mia Rodriguez",
      editorTitle: "Licensed Esthetician",
      price: 12.99,
      image: "/public/aloe.webp",
      description: "Pure aloe vera gel to cool and soothe sunburns, minor burns, and skin irritation.",
      pros: ["Cooling", "Non-greasy", "Soothing"],
      cons: ["Not for dry skin", "Can be sticky on application"],
      ratingRank: 1,
      awards: ["Best Sunburn Relief"]
    },
  
  ];
  export default skincareData;